language: rust
sudo: required
rust:
  - nightly
  - beta
  - stable
  - 1.22.0 # min. supported rust version
cache: cargo

jobs:
  include:
  - stage: fuzz
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y binutils-dev libunwind8-dev
    rust: stable
    script: cd fuzz && cargo test --verbose && ./travis-fuzz.sh
  - stage: coverage
    if: type = cron || type = push
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install cmake g++ pkg-config jq libcurl4-openssl-dev libelf-dev libdw-dev binutils-dev libiberty-dev
      - cargo install -f cargo-kcov
      - for i in {0..10}; do echo "retry $i"; (cargo kcov --print-install-kcov-sh | sh) && break; done
    rust: stable
    script: bash .travis-kcov.sh